name: build and tag

on:
  push:
    tags:
      - '*'
      
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set env for release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print release information
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}    

      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build --progress=plain -t ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF##*/} .
        
      - name: Tag image
        run: docker tag ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF##*/} ghcr.io/rob-luke/fnirs-apps-quality-reports/app:${{ env.RELEASE_VERSION }}

      - name: Push image to github
        run: docker push ghcr.io/rob-luke/fnirs-apps-quality-reports/app:${{ env.RELEASE_VERSION }}

      - name: Tag image
        run: docker tag ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF##*/} ghcr.io/rob-luke/fnirs-apps-quality-reports/app

      - name: Push image to github
        run: docker push ghcr.io/rob-luke/fnirs-apps-quality-reports/app:latest

      - name: Download test data
        shell: bash -el {0}
        run: |
          curl -L https://github.com/rob-luke/BIDS-NIRS-Tapping/archive/master.zip --output data.zip
          pwd
          unzip data.zip -d ~/example_data
          ls

      - name: Build docker image
        run: docker build --progress=plain -t test .
        
      - name: Run docker image
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --sci-threshold 0.6 --pp-threshold 0.6
    
      - name: Copy example report
        shell: bash -el {0}
        run: |
          ls /home/runner
          ls /home/runner/example_data
          ls /home/runner/example_data/BIDS-NIRS-Tapping-master
          ls /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives
          ls /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives/fnirs-apps-quality-reports
          ls /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives/fnirs-apps-quality-reports/sub-04
          ls /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives/fnirs-apps-quality-reports/sub-04/nirs

      - name: Commit documentation changes
        run: |
          pwd
          git clone https://github.com/rob-luke/fnirs-apps-quality-reports.git --branch gh-pages --single-branch /home/runner/gh-pages
          cp /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives/fnirs-apps-quality-reports/sub-04/nirs/sub-04_task-Tapping_qualityReport.html /home/runner/gh-pages/example_report.html
          cd /home/runner/gh-pages
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "Robert Luke"
          git add example_report.html
          git commit -m "Update report" -a || true
          # The above command will fail if no changes were present, so we ignore that.
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: /home/runner/gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
